### ISSUE TITLE
Issue with bbPress breadcrumb path

### ISSUE THREAD

**Issue by ajtruckle** [mtekk/Breadcrumb-NavXT#245] opened 2020-07-07 21:31 UTC
I thought I would start a new issue rather than continue to hijack the [other one](https://github.com/mtekk/Breadcrumb-NavXT-bbPress-Extensions/issues/3).

I am using the latest code on GitHub for both the master plugin and bbPress extension. And I have set up the settings was was suggested to me for bbPress compatibility.

It would see that my Public forum usually is showing the correct breadcrumbs:

![BreadCrumbs3](https://user-images.githubusercontent.com/7985331/86844702-54e7d000-c0a0-11ea-878f-89456a3413ed.png)

The link to the topic is:

https://www.publictalksoftware.co.uk/support-forums/topic/are-publishers-able-to-use-meeting-schedule-assistant/

As you can see the BreadCrumbs Navx and bbp style pack are pretty much the same.

But the moment I click on **Frequently Asked Questions** in your breadcrumb list the breadcrumb becomes:

`Theocratic Software > Support Forum > Forums > Frequently Asked Questions`

It is missing a level:

`Support Forum › General Information › Frequently Asked Questions`

**General Information** is no longer there.

bbp style pack breadcrumbs are always 100% correct and should be used as a basis to establish why the breadcrumb navx is falling over.

Take this one:

https://www.publictalksoftware.co.uk/support-forums/topic/working-with-the-new-host-and-co-host-database-fields/

You need to be registered to view that page. The breadcrumbs returned are:

`Breadcrumbs Navx: Theocratic Software > Forums > Working with the new Host and Co-host database fields`
`bbp style pack:        Support Forum › Public Talks › Custom Report Scripts › Working with the new Host and Co-host database fields`

Forums - Support Forum are one and the same, although I am not sure why I can use the word Support Forum in your breadcrumb list. But Public Talks | Custom Report Scripts are missing.

**Comment by ajtruckle** [comment] 2020-07-09 11:11
Any clarification about this please? Thank you.

**Comment by mtekk** [comment] 2020-07-12 21:38
It looks like you are using hierarchical forums, which is fine, you will just need to make sure "Forum Hierarchy Display" is checked and "Forum Hierarchy" is set to "Post Parent". I don't remember the reasoning behind the recommendation of not enabling that for the Forum post type (I'm assuming it was an oversight as I didn't have a sub forum on my testbed, not sure if it was supported back in 2014 when I initially looked at bbPress support).

**Comment by ajtruckle** [comment] 2020-07-12 21:49
Hi

Thanks for that. I am afraid it doesn't seem to make any difference.

I don't understand it because the bbp style pack plugin breadcrumb display is 100% correct and I am unsure why your plugin isn't following the same logic.

For some reason I am doing something wrong.

**Comment by mtekk** [comment] 2020-07-12 22:06
Can you check the page again? When I visit, I see the breadcrumb trail as:
`Theocratic Software > Support Forum > Forums > General Information > Frequently Asked Questions`

Which is correct, other than the fact that you probably don't need both a root page and archive for the forums.

**Comment by ajtruckle** [comment] 2020-07-12 22:10
That forum is OK. But it is the only one that is OK. Temporarily register with my forum (I will approve your account) and you have a look at all of the private forums. They are not correct.

**Comment by mtekk** [comment] 2020-07-12 22:26
Ok, that's interesting. After seeing how the rest of your forum is behaving, the good news is I can reproduce that on my testbed as well. I'm going to dig into this some more.

**Comment by ajtruckle** [comment] 2020-07-12 22:27
Thank you very much. I am glad you are able to reproduce and appreciate your time in looking for a solution.

**Comment by mtekk** [comment] 2020-07-12 22:39
So, bbPress is using the private attribute for the post type. Which is fine, however, a change made to Breadcrumb NavXT 6.4.0 hides breadcrumbs for posts marked as private. However, at the same time a new filter `bcn_show_post_private` was added. In a site specific plugin, or theme functions.php the following code can be placed to enable the display of breadcrumbs for private forums in the breadcrumb trail:

`add_filter('bcn_show_post_private', 'my_bcn_show_post_private', 10, 2);
function my_bcn_show_post_private($show, $ID)
{
	$post = get_post($ID);
	if($post instanceof WP_Post && $post->post_type === 'forum')
	{
		$show = true;
	}
	return $show;
}`

**Comment by ajtruckle** [comment] 2020-07-12 22:44
Excellent! Now the forums show the correct paths! Well done!

So the only remaining question is (which is not a big issue). Take:

`Theocratic Software > Forums > Meeting Schedule Assistant > Midweek Editor — Template Samples > Workbook Schedule – Compact Style`

Is it possible for "Forums" to actually be "Support Forum"? That is the only minor issue. Is that a setting?

**Comment by mtekk** [comment] 2020-07-13 02:30
In theory, you should be able to use the "Root Page", setting it to the Page with the same slug as set in the bbPress "Forum Root" setting. Additionally, you will want to have the "Forum Archive Display" setting unchecked. This combination of settings seems to work on my testbed.

**Comment by ajtruckle** [comment] 2020-07-13 03:51
Awesome! Thanks! Shall I delete your account now for you?

Thanks for your help!

**Comment by ajtruckle** [comment] 2020-07-13 03:58
One thing I have noticed:

When I deactivate the bbp style pack breadcrumbs, leaving just yours, then it starts to display **Private:** prefix again in front of the breadcrumb entries. I don’t like this.

I at moment I have switched his breadcrumbs back on because this hides that prefix for me. Can we do the same via your plugin? Then I can finally switch the setting off. Or, do you prefer this as a new issue? Thanks!

**Comment by ajtruckle** [comment] 2020-07-13 08:15
> When I deactivate the bbp style pack breadcrumbs, leaving just yours, then it starts to display **Private:** prefix again in front of the breadcrumb entries. I don’t like this.

What I have done is deactivate the bbp style pack breadcrumbs. Now, when we look [here ](https://www.publictalksoftware.co.uk/support-forums/forum/meeting-schedule-assistant/midweek-editor/)we get:

`Theocratic Software > Support Forum > Meeting Schedule Assistant > Midweek Editor`

Great! But, if we then go drill down to an actual topic (eg [here](https://www.publictalksoftware.co.uk/support-forums/topic/10-19-s-89-student-assignment-slip/)):

`Theocratic Software > Private: Meeting Schedule Assistant > Private: Midweek Editor > 10/19 S-89 Student Assignment Slip`

As you can see, it has changed and is now showing the **Private:** prefix. This prefix is removed when I use the bbp style pack breadcrumbs. Are we able to do the same thing with Breadcrumbs NavXT?

**Comment by mtekk** [comment] 2020-07-14 02:19
Yeah, that's WordPress "helping" us. Try the following in a site-specific plugin (the same file you put the previous filter I posted would be a good spot):
`add_filter('private_title_format', 'my_private_title_format', 10, 2);
function my_private_title_format($format, $post)
{
	if($post instanceof WP_Post && ($post->post_type === 'forum' || $post->post_type === 'topic'))
	{
		$format = '%s';
	}
	return $format;
}`

It should remove the "Private: " prefix from the titles of forum and topic post types.

**Comment by ajtruckle** [comment] 2020-07-14 04:28
Fantastic! You are very clever.
Seems all ok now.
Shall I delete your user profile?

**Comment by mtekk** [comment] 2020-07-15 00:30
Yes, you can delete my user profile on your site.

**Closed** 2020-07-15 04:37 UTC
