### ISSUE TITLE
Translation loading triggered too early for breadcrumb-navxt domain

### ISSUE THREAD

**Issue by emon4u** [mtekk/Breadcrumb-NavXT#308] opened 2024-12-17 13:34 UTC
I encountered the following notice in my WordPress site:

`Notice: Function _load_textdomain_just_in_time was called incorrectly. Translation loading for the breadcrumb-navxt domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the init action or later. Please see Debugging in WordPress for more information. (This message was added in version 6.7.0.) in /home/u552154654/domains/pixelfit.agency/public_html/wp/sasfy/wp-includes/functions.php on line 6114`

**Steps to Reproduce:**
1. Install and activate the Breadcrumb NavXT plugin.
2. Enable WP_DEBUG to see notices.
3. Visit the frontend or admin panel of the site.

**Expected Behavior:**
Translations for the breadcrumb-navxt text domain should load without triggering a notice.

**Actual Behavior:**
The notice indicates that translation loading is triggered too early, suggesting that the code might be running before the init action.

**Environment Details:**
1. Breadcrumb NavXT Version: 7.3.1
2. WordPress Version: 6.7.1
3. PHP Version: 8.1

**Suggested Solution:**
Ensure that the translation loading logic for the breadcrumb-navxt domain is executed at the init action or later to comply with WordPress standards.

**Comment by mtekk** [comment] 2024-12-18 01:42
This looks to be a duplicate of #303, which has been fixed in the [volleyballer](https://github.com/mtekk/Breadcrumb-NavXT/tree/volleyballer) branch. This will be part of the upcoming 7.4 release.

**Comment by emon4u** [comment] 2024-12-18 05:58
Thank you for the prompt response! It's great to hear that the issue is already addressed in the volleyballer branch. Could you please share an approximate timeline for the 7.4 release?

Thanks again for your hard work on this plugin!

**Comment by mtekk** [comment] 2024-12-22 14:52
The goal is before the end of 2024 for the release of 7.4

**Closed** 2024-12-23 06:35 UTC
